### ISSUE TITLE
Add numbers-by-matrices multiplication

### ISSUE THREAD

**Issue by Ashotyanski** [kyonifer/golem#28]
Currently the Matrix interface has `times()` operator for multiplying by both other matrices and numbers.
Hence, this code is correct: 
`var mulMatByTwo = ones(1) * 2.0`

But as `times()` operator is not extended in the Int and Double classes, such code is incorrect:
`var mulTwoByMat = 2.0 * ones(1)`
which means multiplication is not commutative.

For the sake of consistency, we can create an extension in the Number class:
`operator fun <M : Number> Number.times(other: Matrix<M>): Matrix<Double> {
    return other * this
}`

**Comment by kyonifer** [comment]
Thanks for the ticket.

I've got `times` extension functions for `Int` and `Double` [here](https://github.com/kyonifer/golem/blob/master/golem-core/src/golem/operators.kt#L68), so the following should work:

```kotlin
import golem.*
fun foo() {
    val a = -1*zeros(3,3)
}
```
Let me know if you have any issues with it.

**Comment by Ashotyanski** [comment]
Yes, `import golem.*` fixed the problem, thanks.
