### ISSUE TITLE
Provide public artifact id

### ISSUE THREAD

**Issue by holgerbrandl** [kyonifer/golem#4]
Would it be possible to provide a public (e.g. Jcenter/bintray) artifact id for golem?

**Comment by kyonifer** [comment]
There's currently an artifact on jcenter, you should be able to include it in gradle with

```groovy
compile 'golem:golem:0.5'
```

Note that the current artifact brings in all the matrix backends as dependencies. I'm in the process of refactoring into split artifacts so you can select one based on which backend you want. I'll leave this issue open until I complete that and update the docs.

**Comment by kyonifer** [comment]
Current build has artifacts for backends and core, with docs in the README.
